### ISSUE TITLE
Bug OCPP Connector no editable in some charging station

### ISSUE THREAD

**Issue by fcoutellier** [LucasBrazi06/ev-dashboard#1688]
Depending on the charging station the connector are not any longer visible in edit mode

![image.png](https://images.zenhubusercontent.com/5e411e0517fa45e1af2c53aa/8bdec30c-a967-49c2-b067-5da2cd3c4220)
![image.png](https://images.zenhubusercontent.com/5e411e0517fa45e1af2c53aa/c3cb697e-6b83-4ee5-b3cd-f59f1e0a1196)
![image.png](https://images.zenhubusercontent.com/5e411e0517fa45e1af2c53aa/5f9d144a-3c11-4096-8fcc-2bca2a1de7af)

[
      {
            "stack": "TypeError: Cannot read property 'value' of undefined
   at OCPPService.stopOrDeleteActiveTransactions (/home/vcap/app/dist/webpack:/src/server/ocpp/services/OCPPService.ts:1795:77)
   at OCPPService.handleStartTransaction (/home/vcap/app/dist/webpack:/src/server/ocpp/services/OCPPService.ts:612:7)
   at JsonChargingStationService.handle (/home/vcap/app/dist/webpack:/src/server/ocpp/json/services/JsonChargingStationService.ts:113:14)
   at JsonChargingStationService.handleStartTransaction (/home/vcap/app/dist/webpack:/src/server/ocpp/json/services/JsonChargingStationService.ts:80:20)
   at JsonWSConnection.handleRequest (/home/vcap/app/dist/webpack:/src/server/ocpp/json/JsonWSConnection.ts:112:22)
   at JsonWSConnection.onMessage (/home/vcap/app/dist/webpack:/src/server/ocpp/json/WSConnection.ts:144:11)"
      }
]

**Comment by LucasBrazi06** [comment]
For the connector not visible, I fixed it this week-end :-)
For the OCPP one I just fixed it ;-)
I move this issue to QA

**Comment by fcoutellier** [comment]
@LucasBrazi06 Excellent!!! I guess that we should reassign the OCPP issues to other dev right?

**Comment by LucasBrazi06** [comment]
> @LucasBrazi06 Excellent!!! I guess that we should reassign the OCPP issues to other dev right?

I also fixed it but not yet deployed ;-)
